/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReturnsRouteImport } from './routes/returns'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as RentalsRouteImport } from './routes/rentals'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as OwnersRouteImport } from './routes/owners'
import { Route as ExchangesRouteImport } from './routes/exchanges'
import { Route as EquipmentRouteImport } from './routes/equipment'
import { Route as DuesRouteImport } from './routes/dues'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as IndexRouteImport } from './routes/index'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnsRoute = ReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const RentalsRoute = RentalsRouteImport.update({
  id: '/rentals',
  path: '/rentals',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnersRoute = OwnersRouteImport.update({
  id: '/owners',
  path: '/owners',
  getParentRoute: () => rootRouteImport,
} as any)
const ExchangesRoute = ExchangesRouteImport.update({
  id: '/exchanges',
  path: '/exchanges',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipmentRoute = EquipmentRouteImport.update({
  id: '/equipment',
  path: '/equipment',
  getParentRoute: () => rootRouteImport,
} as any)
const DuesRoute = DuesRouteImport.update({
  id: '/dues',
  path: '/dues',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/customers': typeof CustomersRoute
  '/documents': typeof DocumentsRoute
  '/dues': typeof DuesRoute
  '/equipment': typeof EquipmentRoute
  '/exchanges': typeof ExchangesRoute
  '/owners': typeof OwnersRoute
  '/payments': typeof PaymentsRoute
  '/rentals': typeof RentalsRoute
  '/reports': typeof ReportsRoute
  '/returns': typeof ReturnsRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/customers': typeof CustomersRoute
  '/documents': typeof DocumentsRoute
  '/dues': typeof DuesRoute
  '/equipment': typeof EquipmentRoute
  '/exchanges': typeof ExchangesRoute
  '/owners': typeof OwnersRoute
  '/payments': typeof PaymentsRoute
  '/rentals': typeof RentalsRoute
  '/reports': typeof ReportsRoute
  '/returns': typeof ReturnsRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/customers': typeof CustomersRoute
  '/documents': typeof DocumentsRoute
  '/dues': typeof DuesRoute
  '/equipment': typeof EquipmentRoute
  '/exchanges': typeof ExchangesRoute
  '/owners': typeof OwnersRoute
  '/payments': typeof PaymentsRoute
  '/rentals': typeof RentalsRoute
  '/reports': typeof ReportsRoute
  '/returns': typeof ReturnsRoute
  '/settings': typeof SettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/customers'
    | '/documents'
    | '/dues'
    | '/equipment'
    | '/exchanges'
    | '/owners'
    | '/payments'
    | '/rentals'
    | '/reports'
    | '/returns'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/customers'
    | '/documents'
    | '/dues'
    | '/equipment'
    | '/exchanges'
    | '/owners'
    | '/payments'
    | '/rentals'
    | '/reports'
    | '/returns'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/customers'
    | '/documents'
    | '/dues'
    | '/equipment'
    | '/exchanges'
    | '/owners'
    | '/payments'
    | '/rentals'
    | '/reports'
    | '/returns'
    | '/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CustomersRoute: typeof CustomersRoute
  DocumentsRoute: typeof DocumentsRoute
  DuesRoute: typeof DuesRoute
  EquipmentRoute: typeof EquipmentRoute
  ExchangesRoute: typeof ExchangesRoute
  OwnersRoute: typeof OwnersRoute
  PaymentsRoute: typeof PaymentsRoute
  RentalsRoute: typeof RentalsRoute
  ReportsRoute: typeof ReportsRoute
  ReturnsRoute: typeof ReturnsRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/returns': {
      id: '/returns'
      path: '/returns'
      fullPath: '/returns'
      preLoaderRoute: typeof ReturnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rentals': {
      id: '/rentals'
      path: '/rentals'
      fullPath: '/rentals'
      preLoaderRoute: typeof RentalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owners': {
      id: '/owners'
      path: '/owners'
      fullPath: '/owners'
      preLoaderRoute: typeof OwnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exchanges': {
      id: '/exchanges'
      path: '/exchanges'
      fullPath: '/exchanges'
      preLoaderRoute: typeof ExchangesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipment': {
      id: '/equipment'
      path: '/equipment'
      fullPath: '/equipment'
      preLoaderRoute: typeof EquipmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dues': {
      id: '/dues'
      path: '/dues'
      fullPath: '/dues'
      preLoaderRoute: typeof DuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CustomersRoute: CustomersRoute,
  DocumentsRoute: DocumentsRoute,
  DuesRoute: DuesRoute,
  EquipmentRoute: EquipmentRoute,
  ExchangesRoute: ExchangesRoute,
  OwnersRoute: OwnersRoute,
  PaymentsRoute: PaymentsRoute,
  RentalsRoute: RentalsRoute,
  ReportsRoute: ReportsRoute,
  ReturnsRoute: ReturnsRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
